version: 2
updates:   
     - package-ecosystem: gradle
    # Look for a `Dockerfile` in the `root` directory
    directory: "/app"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 20
